# Generated by Django 3.2.20 on 2023-12-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actual', models.DateField()),
                ('periodo', models.CharField(max_length=20)),
                ('id_alumno', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('id_sexo', models.CharField(choices=[('1', 'Hombre'), ('2', 'Mujer')], max_length=1)),
                ('edad', models.CharField(max_length=3)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(choices=[('1', 'Soltero(a)'), ('2', 'Casado(a)'), ('3', 'Unión libre'), ('4', 'Viudo(a)'), ('5', 'Divorciado(a)')], max_length=1)),
                ('telefono_celular', models.CharField(max_length=15)),
                ('carrera', models.CharField(max_length=50)),
                ('semestre', models.CharField(max_length=20)),
                ('ocupacion', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('condicion_salud', models.CharField(max_length=200)),
                ('fecha_inicio_condicion', models.DateField()),
                ('tratamiento', models.CharField(choices=[('1', 'Sí'), ('2', 'No')], max_length=1)),
                ('atentado', models.CharField(choices=[('1', 'Ideación suicida'), ('2', 'Planeación suicida'), ('3', 'Intento suicida'), ('4', 'Ninguno')], max_length=1)),
                ('fecha_atentado', models.DateField()),
                ('descripcion_atentado', models.CharField(max_length=200)),
                ('numero_emergencia', models.CharField(max_length=15)),
                ('contacto_emergencia', models.CharField(max_length=100)),
                ('parentesco_contacto_e', models.CharField(choices=[('1', 'Padre'), ('2', 'Madre'), ('3', 'Hermano'), ('4', 'Hermana'), ('5', 'Pareja'), ('6', 'Amistad')], max_length=1)),
                ('conocimiento_servicio', models.CharField(choices=[('1', 'Por un amigo (a)'), ('2', 'Por publicación del grupo de teams'), ('3', 'Por indicación de un docente'), ('4', 'Por indicación de mi tutor (a)'), ('5', 'Por el servicio de enfermería'), ('6', 'Por la propaganda pegada en las paredes de la institución'), ('7', 'Otro')], max_length=1)),
                ('motivo_consulta', models.CharField(choices=[('1', 'Académico'), ('2', 'Personal'), ('3', 'Familiar'), ('4', 'Social')], max_length=1)),
                ('descripcion_consulta', models.CharField(max_length=200)),
                ('expectativas_usuario', models.CharField(max_length=200)),
            ],
        ),
    ]
