# Generated by Django 3.2.20 on 2023-12-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='id',
        ),
        migrations.AlterField(
            model_name='registro',
            name='id_alumno',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
